name: surveyor
description: Tools for surveying Dart sources
version: 0.0.1
homepage: https://github.com/pq/surveyor

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  analyzer: ^0.37.0
  cli_util: ^0.1.3
  http: ^0.12.0
  pub_semver: ^1.0.0
  tuple: ^1.0.0

dev_dependencies:
  pedantic: ^1.0.0
