name: surveyor
description: Tools for surveying Dart sources
version: 0.1.0
homepage: https://github.com/pq/surveyor

# Not intended for publishing.
publish_to: none

environment:
  sdk: '>=2.17.0-0 <3.0.0'

dependencies:
  analyzer: ^3.0.0
  args: ^2.0.0
  cli_util: ^0.3.0
  http: ^0.13.0
  linter:  ^1.0.0
  path: ^1.8.0
  pub_semver: ^2.0.0
  yaml: ^3.1.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.20.0
